### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by quasiDigi** [ACP-CODE/astro-favicons#10]
Well, it's more a feature request than an issue, but it would be nice to have multilingual support, working the i18n implementation in Astro.

This could look like:

```
export default defineConfig({
  // ...
  integrations: [
    favicons({
      // ...
      appDescription: { 
            'en' : 'English description',
            'es' : 'Descripción en Español',
            'zh': '中文描述'
      },
      lang: {
            'en' : 'en-US',
            'es' : 'es-ES',
            'zh' : 'zh-CN',
      }
      // ....
    }),
  ],
});
```

Thanks!

**Comment by JakiChen** [comment]
Heyyy @quasiDigi , 

Migrate to astro-favicons 3.0+ , `localized` support now.

If you have any questions, improvements, or contributions, please give us feedback, thanks
