### ISSUE TITLE
'path' is required in config, but not documented

### ISSUE THREAD

**Issue by silveltman** [ACP-CODE/astro-favicons#11]
I get the following ts error 
```
Property 'path' is missing in type '{ masterPicture: string; appName: string; appShortName: string; }' but required in type 'FaviconConfig'.
```

config:
```
    favicons({
      masterPicture: '/images/favicons/master.png',
      appName: 'FullDev UI',
      appShortName: 'FullDev UI',
    }),
```

Path is not documented as far as I see. Is this new name for masterPicture?

**Comment by JakiChen** [comment]
heyyyy, @silveltman 

If `masterPicture: '/images/favicons/master.png'`, is set to that value, you should get the following error

```
yarn run v1.22.22
$ astro dev
node:internal/fs/promises:639
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/images/favicons/favicon-32x32.png'
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async sourceImages (file:///Users/JakiChen/Desktop/cloudflare/node_modules/favicons-lib/dist/index.mjs:180:20)
    at async favicons (file:///Users/JakiChen/Desktop/cloudflare/node_modules/favicons-lib/dist/index.mjs:966:21)
    at async vitePluginFavicons (file:///Users/JakiChen/Desktop/cloudflare/node_modules/astro-favicons/dist/index.js:111:20) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/images/favicons/favicon-32x32.png'
}

Node.js v20.18.0
```

The correct configuration should be **`masterPicture: "./images/favicons/master.png"`** , or use the default value (only `favicon.svg` or other format in the `src` root directory)

> Tip: When you run` npm run dev` for the first time, the favicons related code will be placed between the heads of each page (the icon resource is not generated at this time), in order to see the icon effect, it is recommended to generate the icon to the public directory through `npm run astro build` for the first time)

**Comment by JakiChen** [comment]
heyyy, @silveltman 

```js
......
favicons({
      masterPicture: './images/favicons/favicon-32x32.png'
    })
.....
```

If the masterPicture is configured correctly, you should be able to get the generated file as shown in the image by `npm run astro build` or `npm run build`, please refer to the documentation for more details.

<img width="1093" alt="截屏2024-10-19 15 40 45" src="https://github.com/user-attachments/assets/9465b145-24fb-40f1-8ac9-34aeb89258b9">

:-) Happy Coding!

**Comment by silveltman** [comment]
Thanks for the quick response @JakiChen , but I think you misunderstood me. Everything is working fine, I get no runtime errors. I only get TS intellisense error.  Please see screenshots below

config where everything works and no ts errors:
![Screen Cursor 19-10-2024 12 22 46](https://github.com/user-attachments/assets/a9e7dacd-29ab-4702-9230-304dcdf7c033)

No ts errors, but not working due to missing picture:
![Screen Cursor 19-10-2024 12 23 10](https://github.com/user-attachments/assets/3ec5de76-00fe-4f33-87ef-c2dff751f1d6)

Working correctly, but giving false ts error:
![Screen Cursor 19-10-2024 12 23 38](https://github.com/user-attachments/assets/a4d3efbf-d51f-4926-8e08-d2a95e3e38b1)

**Comment by silveltman** [comment]
This also works fine, the path key does nothing

![Screen Cursor 19-10-2024 12 24 34](https://github.com/user-attachments/assets/4df85a36-3549-47fc-85a5-e92f6b942d61)

**Comment by JakiChen** [comment]
`./src/images/favicon.svg` not `src/images/favicon.svg`

If you are not used to it, you don’t need to change the masterPicure (defatul: `./src/favcion.svg`), just provide `favicon.svg` in the src directory

**Comment by JakiChen** [comment]
@silveltman 

`./src/images/favicon.svg` not your setting `src/images/favicon.svg`

或其它任意目录 `./images/path/favicon.svg` 而不是 `images/path/favicon.svg`

If you are not used to it, you don’t need to change the masterPicure (defatul: `./src/favcion.svg`), just provide a `favicon.svg` in the `src` directory

**Comment by JakiChen** [comment]
heyyy, @silveltman 

This ts prompt appears: You should use the `astro.config.ts` file instead of `astro.config.mjs`

And intrface `path: string`;  is the parameter that controls the icon generation directory. The default configuration is "/" (public root directory). The reason why the ts error appears here is that path?: string; is not set in inde.d.ts.

Since not many people use it, there is no time to update the integration recently, please understand.

If you want to quickly eliminate this error prompt, you can use `astro.config.mjs` or update path?: string; in index.d.ts in astro-favicons

It may be updated in the near future to support the splash screen of more new devices

Thank you for your feedback and wish you a happy work
