### ISSUE TITLE
Support for Astro 5+

### ISSUE THREAD

**Issue by michaelpumo** [ACP-CODE/astro-favicons#29]
Hi there,

Just updated to Astro `5.0.1` but the peer dependency for this package is Astro `^4.0.0`.

```
npm error Found: astro@5.0.1
npm error node_modules/astro
npm error   astro@"^5.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer astro@"^4.0.0" from astro-favicons@2.1.8
npm error node_modules/astro-favicons
npm error   astro-favicons@"^2.1.8" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

Thank you.

**Comment by JakiChen** [comment]
There will be a new version 3.0.0

- Brand new API,
- Capo.js support
- You can set icons for each platform, or use the default `public/favicons.svg` to generate all icon materials.
- Screenshot support
- New manifest object (flexible extension of manifest standards unique to platforms such as edge)
- Out of the box, you can preview all resources in development mode, without the need to pre-generate resources through building before using them as before

And so on, I hope I won’t bother you, and I wish you a happy coding

**Comment by JakiChen** [comment]
Migrate to astro-favicons 3.0+ now, See [3.0.2](https://github.com/ACP-CODE/astro-favicons/releases/tag/v3.0.2) for change log

If you have any questions, improvements, or contributions, please give us feedback, thanks
