### ISSUE TITLE
[Features] - Add a tag element

### ISSUE THREAD

**Issue by Robin-Wils** [ACP-CODE/astro-favicons#30]
It would be useful to have a tag element to be able to put the favicon tags in the correct location. This is especially interesting when combined with astro-capo.

https://github.com/natemoo-re/astro-capo

**Comment by JakiChen** [comment]
Heyyyy, @Robin-Wils 

Migrate to astro-favicons 3.0+ now, See [3.0.2](https://github.com/ACP-CODE/astro-favicons/releases/tag/v3.0.2) for change log

If you have any questions, improvements, or contributions, please give us feedback, thanks

**Comment by Robin-Wils** [comment]
Hi thanks for the quick update. 

**Astro-capo**
The astro-capo support turned out a bit different than expected, but it is nice. What I expected was just a tag which would have the favicons meta tags, example:

```xml
<Head>
    <MyFavIconsComponent />
    <meta name="some other meta tag" content="some content" />
    <script type="application/ld+json" set:html={schemaJson} />
</Head>
```
That is how astro-seo has support for astro-capo, without having to include astro-capo itself. 
  
**New options**
But the update is appreciated! The new options look cool, but aren't documented well yet. Previously I could set description, but I no longer know how I can do that now.
