### ISSUE TITLE
warning: Sourcemap is likely to be incorrect

### ISSUE THREAD

**Issue by silveltman** [ACP-CODE/astro-favicons#7]
When using this plugin, i get the following warning spammed like 2000 times in my console on astro dev and astro build:
```
(vite-plugin-astro-bookshop plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-astro-bookshop) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
(vite-plugin-favicons plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-favicons) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

Both are getting logged one after the other. When not using this integration, the other package does not log this. I will make an issue for the on the other package as well.

**Comment by JakiChen** [comment]
heyyy, @silveltman 

This may be fixed. But I'm still not very sure, so I just rolled back to the previous version.
If you have any other feedback about "astro-favicons", please update it in time. Thank you again.

https://github.com/ACP-CODE/astro-favicons/blob/8f70053e913ddbe056a5021014f19d2c251d3848/src/core.ts#L151

**Comment by JakiChen** [comment]
dd
